
module MoveSeeds

  def self.air_moves_1
    [{name: "Static skin",
      type: "utility",
      realm: "corporeal",
      element: "air",
      power: 3,
      cost: 3,
      effect1: ["buff","res",1,1,3],
      effect2: "reflect",
      cooldown: 2,
      cooldown_total: 2,
      rank: 1,
      tier: 1
    },
    { name: "Electric touch",
      type: "damage",
      realm: "corporeal",
      element: "air",
      power: 10,
      cost: 1,
      effect1: ["buff","atk",1,1,3],
      effect2: "",
      cooldown: 1,
      cooldown_total: 1,
      rank: 1,
      tier: 1
    },
    { name: "Wind blast",
      type: "damage",
      realm: "ethereal",
      element: "air",
      power: 25,
      cost: 3,
      effect1: ["debuff","res",-2,1,3],
      effect2: "",
      cooldown: 2,
      cooldown_total: 2,
      rank: 1,
      tier: 1
    },
     { name: "Static shock",
      type: "damage",
      realm: "ethereal",
      element: "air",
      power: 15,
      cost: 1,
      effect1: [],
      effect2: "",
      cooldown: 1,
      cooldown_total: 1,
      rank: 1,
      tier: 1
    },
    { name: "Thunder rush",
      type: "damage",
      realm: "corporeal",
      element: "air",
      power: 10,
      cost: 2,
      effect1: ["buff","spd",2,1,3],
      effect2: "",
      cooldown: 1,
      cooldown_total: 1,
      rank: 1,
      tier: 1
    }]
  end


  def self.water_moves_1
    [{ name: "Splash",
      type: "heal",
      realm: "ethereal",
      element: "water",
      power: 15.0,
      cost: 2,
      effect1: [],
      effect2: "",
      cooldown: 2,
      cooldown_total: 2,
      rank: 1,
      tier: 1
    },
    { name: "Douse",
      type: "utility",
      realm: "ethereal",
      element: "water",
      power: 0,
      cost: 1,
      effect1: ["cure","dot",1,1,-1],
      effect2: "",
      cooldown: 1,
      cooldown_total: 1,
      rank: 1,
      tier: 1
    },
    { name: "Squirt",
      type: "damage",
      realm: "ethereal",
      element: "water",
      power: 10.0,
      cost: 2,
      effect1: ["debuff","spd",-1,1,3],
      effect2: "",
      cooldown: 0,
      cooldown_total: 0,
      rank: 1,
      tier: 1
    },
    { name: "Ice slash",
      type: "damage",
      realm: "corporeal",
      element: "water",
      power: 30.0,
      cost: 1,
      effect1: [],
      effect2: "",
      cooldown: 2,
      cooldown_total: 2,
      rank: 1,
      tier: 1
    },
    { name: "Chill blaines",
      type: "damage",
      realm: "ethereal",
      element: "water",
      power: 15,
      cost: 2,
      effect1: ["dot","hp",-2,1,3],
      effect2: "",
      cooldown: 1,
      cooldown_total: 1,
      rank: 1,
      tier: 1
    },
    { name: "Icy Shard",
      type: "damage",
      realm: "corporeal",
      element: "water",
      power: 25,
      cost: 2,
      effect1: [],
      effect2: "",
      cooldown: 0,
      cooldown_total: 0,
      rank: 1,
      tier: 1
    }]
  end

  def self.fire_moves_1
      [{ name: "Singe",
        type: "damage",
        realm: "ethereal",
        element: "fire",
        power: 10.0,
        cost: 2,
        effect1: ["dot", "hp", -1, 1, 3],
        effect2: "",
        cooldown: 1,
        cooldown_total: 1,
        rank: 1,
        tier: 1
      },
      { name: "Warmth",
        type: "heal",
        realm: "ethereal",
        element: "fire",
        power: 5.0,
        cost: 1,
        effect1: [],
        effect2: "",
        cooldown: 0,
        cooldown_total: 0,
        rank: 1,
        tier: 1
      },
    @firey_shell_1 = { name: "Firey shell",
        type: "utility",
        realm: "ethereal",
        element: "fire",
        power: 3,
        cost: 3,
        effect1: ["buff", "def", 1, 1, 3],
        effect2: "reflect",
        cooldown: 2,
        cooldown_total: 2,
        rank: 1,
        tier: 1
      },
      { name: "Molten swipe",
        type: "damage",
        realm: "corporeal",
        element: "fire",
        power: 15.0,
        cost: 2,
        effect1: ["debuff", "def", -1, 1, 3],
        effect2: "",
        cooldown: 0,
        cooldown_total: 0,
        rank: 1,
        tier: 1
      },
      { name: "Pyro slap",
        type: "damage",
        realm: "corporeal",
        element: "fire",
        power: 25.0,
        cost: 3,
        effect1: [],
        effect2: "",
        cooldown: 1,
        cooldown_total: 1,
        rank: 1,
        tier: 1
      },
      { name: "Lava Jet",
        type: "damage",
        realm: "ethereal",
        element: "fire",
        power: 40,
        cost: 2,
        effect1: [],
        effect2: "",
        cooldown: 3,
        cooldown_total: 3,
        rank: 1,
        tier: 1
      }]
  end


end
